---
abstract: 'stop hard-coding your package names'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: package::compute
name: package-compute
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  B::Hooks::Parser: 0.08
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=package-compute
  homepage: https://metacpan.org/release/package-compute
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-package-compute
version: 0.004
